alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: prod-current
    match:
      authority: {}
      path:
        prefix: /
name: monkfish-app
region: nyc
services:
- environment_slug: node-js
  github:
    branch: dev
    deploy_on_push: true
    repo: nexty1982/prod-current
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: prod-current
  source_dir: /
