import { uniqueId } from 'lodash';
import { useAuth } from 'src/context/AuthContext';

interface MenuitemsType {
  [x: string]: any;
  id?: string;
  navlabel?: boolean;
  subheader?: string;
  title?: string;
  icon?: any;
  href?: string;
  children?: MenuitemsType[];
  chip?: string;
  chipColor?: string;
  variant?: string;
  external?: boolean;
}
import {
  IconAperture,
  IconNotes,
  IconCalendar,
  IconMail,
  IconFileDescription,
  IconNotebook,
  IconFileCheck,
  IconPoint,
  IconEdit,
  IconSettings,
  IconUserCircle,
  IconBuildingChurch,
  IconUsers,
  IconLock,
  IconBrain,
  IconBorderAll,
  IconFiles,
  IconChartHistogram,
  IconMessage,
  IconUserPlus,
  IconWriting,
  IconBell,
  IconHeart,
  IconNews,
  IconWorldWww,
  IconShield,
  IconHome,
  IconTerminal,
  IconCode,
  IconBug,
  IconDeviceDesktop,
  IconSitemap,
  IconActivity,
  IconComponents,
  IconForms,
  IconPalette,
  IconUsers,
  IconLayoutDashboard,
  IconRocket,
  IconApps,
  IconDatabase,
  IconLayout,
  IconCalendarEvent,
  IconRadar,
  IconChartLine,
  IconChartBar,
  IconPalette,
  IconMap,
  IconComponents,
  IconStar,
  IconBox,
  IconAdjustments,
} from '@tabler/icons-react';
import OrthodoxChurchIcon from 'src/components/shared/OrthodoxChurchIcon';

const Menuitems: MenuitemsType[] = [
  {
    navlabel: true,
    subheader: '🏠 Dashboards',
  },
  {
    id: uniqueId(),
    title: 'Enhanced Modern Dashboard',
    icon: IconHome,
    href: '/dashboards/modern',
  },
  {
    id: uniqueId(),
    title: 'Admin Dashboard',
    icon: IconShield,
    href: '/dashboards/orthodmetrics',
  },

  {
    navlabel: true,
    subheader: '📰 News & Social',
  },
  {
    id: uniqueId(),
    title: 'Orthodox Headlines',
    icon: IconNews,
    href: '/orthodox-headlines',
  },
  {
    id: uniqueId(),
    title: 'Blog',
    icon: IconWriting,
    href: '/social/blog',
  },
  {
    id: uniqueId(),
    title: 'Friends',
    icon: IconUserPlus,
    href: '/social/friends',
  },
  {
    id: uniqueId(),
    title: 'Chat',
    icon: IconMessage,
    href: '/social/chat',
  },
  {
    id: uniqueId(),
    title: 'Notifications',
    icon: IconBell,
    href: '/social/notifications',
  },

  {
    navlabel: true,
    subheader: '🕍 Church Tools',
  },
  {
    id: uniqueId(),
    title: 'Church Management',
    icon: OrthodoxChurchIcon,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'All Churches',
        icon: IconPoint,
        href: '/apps/church-management',
      },
      {
        id: uniqueId(),
        title: 'Add Church',
        icon: IconPoint,
        href: '/apps/church-management/create',
      },
      {
        id: uniqueId(),
        title: 'Church Setup Wizard',
        icon: IconPoint,
        href: '/apps/church-management/wizard',
      },
      {
        id: uniqueId(),
        title: 'Church Setup',
        icon: IconPoint,
        href: '/apps/client-management/church-setup',
      },
      {
        id: uniqueId(),
        title: 'Church OCR',
        icon: IconPoint,
        href: '/admin/church/:id/ocr',
      },
      {
        id: uniqueId(),
        title: 'Legacy Profile',
        icon: IconPoint,
        href: '/user-profile',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Records Management',
    icon: IconFileDescription,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Records Browser',
        icon: IconPoint,
        href: '/apps/records-ui',
      },
      {
        id: uniqueId(),
        title: 'Records Dashboard',
        icon: IconPoint,
        href: '/apps/records',
      },
      {
        id: uniqueId(),
        title: 'Legacy Records',
        icon: IconPoint,
        href: '/records',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Analytics',
    icon: IconChartHistogram,
    href: '/analytics',
  },
  {
    id: uniqueId(),
    title: 'Orthodox Calendar',
    icon: IconCalendar,
    href: '/apps/liturgical-calendar',
  },

  {
    navlabel: true,
    subheader: '🤖 Orthodox Metrics Admin OMAI Studio',
  },
  {
    id: uniqueId(),
    title: 'OMAI Ultimate Logger',
    icon: IconActivity,
    href: '/admin/omai-logger',
  },
  {
    id: uniqueId(),
    title: 'Build Console',
    icon: IconTerminal,
    href: '/admin/build',
  },
  {
    id: uniqueId(),
    title: 'Site Editor Demo',
    icon: IconEdit,
    href: '/demos/site-editor',
  },
  {
    id: uniqueId(),
    title: 'Auto-Fix Demo',
    icon: IconEdit,
    href: '/demos/auto-fix',
  },
  {
    id: uniqueId(),
    title: 'GitOps Demo',
    icon: IconEdit,
    href: '/demos/gitops',
  },
  {
    id: uniqueId(),
    title: '🐞 VRT Demo',
    icon: IconBug,
    href: '/demos/vrt',
  },
  {
    navlabel: true,
    subheader: '🧩 Site Components',
  },
  {
    id: uniqueId(),
    title: 'Core Components',
    icon: IconComponents,
    children: [
      {
        id: uniqueId(),
        title: 'Form Components',
        icon: IconForms,
        href: '/sandbox/component-preview/core/forms',
      },
      {
        id: uniqueId(),
        title: 'Theme Components',
        icon: IconPalette,
        href: '/sandbox/component-preview/core/theme',
      },
      {
        id: uniqueId(),
        title: 'Feature Components',
        icon: IconUsers,
        href: '/sandbox/component-preview/core/features',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Modernize Components',
    icon: IconLayoutDashboard,
    children: [
      {
        id: uniqueId(),
        title: 'Calendar Components',
        icon: IconCalendarEvent,
        href: '/sandbox/component-preview/modernize/calendar',
      },
      {
        id: uniqueId(),
        title: 'Data Components',
        icon: IconDatabase,
        href: '/sandbox/component-preview/modernize/data',
      },
      {
        id: uniqueId(),
        title: 'Feature Components',
        icon: IconApps,
        href: '/sandbox/component-preview/modernize/features',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Raydar Components',
    icon: IconRocket,
    children: [
      {
        id: uniqueId(),
        title: 'Calendar Components',
        icon: IconCalendarEvent,
        href: '/sandbox/component-preview/raydar/calendar',
      },
      {
        id: uniqueId(),
        title: 'Layout Components',
        icon: IconLayout,
        href: '/sandbox/component-preview/raydar/layout',
      },
      {
        id: uniqueId(),
        title: 'Form Components',
        icon: IconForms,
        href: '/sandbox/component-preview/raydar/forms',
      },
    ],
  },
  {
    id: uniqueId(),
    title: '🧩 Component Library',
    icon: IconBorderAll,
    href: '/sandbox/component-library',
  },

  {
    navlabel: true,
    subheader: '🏗️ Modernize',
  },
  {
    id: uniqueId(),
    title: 'Apps',
    icon: IconApps,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Contacts',
        icon: IconPoint,
        href: '/apps/contacts',
      },
      {
        id: uniqueId(),
        title: 'Chats',
        icon: IconPoint,
        href: '/apps/chats',
      },
      {
        id: uniqueId(),
        title: 'Email',
        icon: IconPoint,
        href: '/apps/email',
      },
      {
        id: uniqueId(),
        title: 'Notes',
        icon: IconPoint,
        href: '/apps/notes',
      },
      {
        id: uniqueId(),
        title: 'Tickets',
        icon: IconPoint,
        href: '/apps/tickets',
      },
      {
        id: uniqueId(),
        title: 'Calendar',
        icon: IconPoint,
        href: '/apps/calendar',
      },
      {
        id: uniqueId(),
        title: 'Kanban',
        icon: IconPoint,
        href: '/apps/kanban',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Pages',
    icon: IconFiles,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Widgets',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Widget Cards',
            icon: IconPoint,
            href: '/widgets/cards',
          },
          {
            id: uniqueId(),
            title: 'Widget Banners',
            icon: IconPoint,
            href: '/widgets/banners',
          },
          {
            id: uniqueId(),
            title: 'Widget Charts',
            icon: IconPoint,
            href: '/widgets/charts',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'UI',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Alert',
            icon: IconPoint,
            href: '/ui-components/alert',
          },
          {
            id: uniqueId(),
            title: 'Accordion',
            icon: IconPoint,
            href: '/ui-components/accordion',
          },
          {
            id: uniqueId(),
            title: 'Avatar',
            icon: IconPoint,
            href: '/ui-components/avatar',
          },
          {
            id: uniqueId(),
            title: 'Chip',
            icon: IconPoint,
            href: '/ui-components/chip',
          },
          {
            id: uniqueId(),
            title: 'Dialog',
            icon: IconPoint,
            href: '/ui-components/dialog',
          },
          {
            id: uniqueId(),
            title: 'List',
            icon: IconPoint,
            href: '/ui-components/list',
          },
          {
            id: uniqueId(),
            title: 'Popover',
            icon: IconPoint,
            href: '/ui-components/popover',
          },
          {
            id: uniqueId(),
            title: 'Rating',
            icon: IconPoint,
            href: '/ui-components/rating',
          },
          {
            id: uniqueId(),
            title: 'Tabs',
            icon: IconPoint,
            href: '/ui-components/tabs',
          },
          {
            id: uniqueId(),
            title: 'Tooltip',
            icon: IconPoint,
            href: '/ui-components/tooltip',
          },
          {
            id: uniqueId(),
            title: 'Transfer List',
            icon: IconPoint,
            href: '/ui-components/transfer-list',
          },
          {
            id: uniqueId(),
            title: 'Typography',
            icon: IconPoint,
            href: '/ui-components/typography',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Charts',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Area Chart',
            icon: IconPoint,
            href: '/charts/area-chart',
          },
          {
            id: uniqueId(),
            title: 'Line Chart',
            icon: IconPoint,
            href: '/charts/line-chart',
          },
          {
            id: uniqueId(),
            title: 'Gradient Chart',
            icon: IconPoint,
            href: '/charts/gredient-chart',
          },
          {
            id: uniqueId(),
            title: 'Candlestick Chart',
            icon: IconPoint,
            href: '/charts/candlestick-chart',
          },
          {
            id: uniqueId(),
            title: 'Column Chart',
            icon: IconPoint,
            href: '/charts/column-chart',
          },
          {
            id: uniqueId(),
            title: 'Doughnut Chart',
            icon: IconPoint,
            href: '/charts/doughnut-pie-chart',
          },
          {
            id: uniqueId(),
            title: 'Radialbar Chart',
            icon: IconPoint,
            href: '/charts/radialbar-chart',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Auth',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Login',
            icon: IconPoint,
            href: '/auth/login',
          },
          {
            id: uniqueId(),
            title: 'Register',
            icon: IconPoint,
            href: '/auth/register',
          },
          {
            id: uniqueId(),
            title: 'Forgot Password',
            icon: IconPoint,
            href: '/auth/forgot-password',
          },
          {
            id: uniqueId(),
            title: 'Two Steps',
            icon: IconPoint,
            href: '/auth/two-steps',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Pricing',
        icon: IconPoint,
        href: '/pages/pricing',
      },
      {
        id: uniqueId(),
        title: 'FAQ',
        icon: IconPoint,
        href: '/pages/faq',
      },
      {
        id: uniqueId(),
        title: 'Account Settings',
        icon: IconPoint,
        href: '/pages/account-settings',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Forms',
    icon: IconForms,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Form Elements',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Autocomplete',
            icon: IconPoint,
            href: '/forms/form-elements/autocomplete',
          },
          {
            id: uniqueId(),
            title: 'Button',
            icon: IconPoint,
            href: '/forms/form-elements/button',
          },
          {
            id: uniqueId(),
            title: 'Checkbox',
            icon: IconPoint,
            href: '/forms/form-elements/checkbox',
          },
          {
            id: uniqueId(),
            title: 'Radio',
            icon: IconPoint,
            href: '/forms/form-elements/radio',
          },
          {
            id: uniqueId(),
            title: 'Slider',
            icon: IconPoint,
            href: '/forms/form-elements/slider',
          },
          {
            id: uniqueId(),
            title: 'Date Time',
            icon: IconPoint,
            href: '/forms/form-elements/date-time',
          },
          {
            id: uniqueId(),
            title: 'Switch',
            icon: IconPoint,
            href: '/forms/form-elements/switch',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Form Layouts',
        icon: IconPoint,
        href: '/forms/form-layouts',
      },
      {
        id: uniqueId(),
        title: 'Form Custom',
        icon: IconPoint,
        href: '/forms/form-custom',
      },
      {
        id: uniqueId(),
        title: 'Form Wizard',
        icon: IconPoint,
        href: '/forms/form-wizard',
      },
      {
        id: uniqueId(),
        title: 'Form Validation',
        icon: IconPoint,
        href: '/forms/form-validation',
      },
      {
        id: uniqueId(),
        title: 'Form Horizontal',
        icon: IconPoint,
        href: '/forms/form-horizontal',
      },
      {
        id: uniqueId(),
        title: 'Form Vertical',
        icon: IconPoint,
        href: '/forms/form-vertical',
      },
      {
        id: uniqueId(),
        title: 'Tiptap Editor',
        icon: IconPoint,
        href: '/forms/form-tiptap',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tables',
    icon: IconBorderAll,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Basic Table',
        icon: IconPoint,
        href: '/tables/basic',
      },
      {
        id: uniqueId(),
        title: 'Enhanced Table',
        icon: IconPoint,
        href: '/tables/enhanced',
      },
      {
        id: uniqueId(),
        title: 'Pagination Table',
        icon: IconPoint,
        href: '/tables/pagination',
      },
      {
        id: uniqueId(),
        title: 'Fixed Header Table',
        icon: IconPoint,
        href: '/tables/fixed-header',
      },
      {
        id: uniqueId(),
        title: 'Collapsible Table',
        icon: IconPoint,
        href: '/tables/collapsible',
      },
      {
        id: uniqueId(),
        title: 'Search Table',
        icon: IconPoint,
        href: '/tables/search',
      },
      {
        id: uniqueId(),
        title: 'React Tables',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Basic',
            icon: IconPoint,
            href: '/react-tables/basic',
          },
          {
            id: uniqueId(),
            title: 'Column Visibility',
            icon: IconPoint,
            href: '/react-tables/column-visiblity',
          },
          {
            id: uniqueId(),
            title: 'Dense',
            icon: IconPoint,
            href: '/react-tables/dense',
          },
          {
            id: uniqueId(),
            title: 'Drag Drop',
            icon: IconPoint,
            href: '/react-tables/drag-drop',
          },
          {
            id: uniqueId(),
            title: 'Editable',
            icon: IconPoint,
            href: '/react-tables/editable',
          },
          {
            id: uniqueId(),
            title: 'Empty',
            icon: IconPoint,
            href: '/react-tables/empty',
          },
          {
            id: uniqueId(),
            title: 'Expanding',
            icon: IconPoint,
            href: '/react-tables/expanding',
          },
          {
            id: uniqueId(),
            title: 'Filter',
            icon: IconPoint,
            href: '/react-tables/filter',
          },
          {
            id: uniqueId(),
            title: 'Pagination',
            icon: IconPoint,
            href: '/react-tables/pagination',
          },
          {
            id: uniqueId(),
            title: 'Row Selection',
            icon: IconPoint,
            href: '/react-tables/row-selection',
          },
          {
            id: uniqueId(),
            title: 'Sorting',
            icon: IconPoint,
            href: '/react-tables/sorting',
          },
          {
            id: uniqueId(),
            title: 'Sticky',
            icon: IconPoint,
            href: '/react-tables/sticky',
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Mui Charts',
    icon: IconChartHistogram,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Bar Charts',
        icon: IconPoint,
        href: '/muicharts/barcharts',
      },
      {
        id: uniqueId(),
        title: 'Gauge Charts',
        icon: IconPoint,
        href: '/muicharts/gaugecharts',
      },
      {
        id: uniqueId(),
        title: 'Line Charts Area',
        icon: IconPoint,
        href: '/muicharts/linecharts/area',
      },
      {
        id: uniqueId(),
        title: 'Line Charts',
        icon: IconPoint,
        href: '/muicharts/linecharts/line',
      },
      {
        id: uniqueId(),
        title: 'Pie Charts',
        icon: IconPoint,
        href: '/muicharts/piecharts',
      },
      {
        id: uniqueId(),
        title: 'Scatter Charts',
        icon: IconPoint,
        href: '/muicharts/scattercharts',
      },
      {
        id: uniqueId(),
        title: 'Sparkline Charts',
        icon: IconPoint,
        href: '/muicharts/sparklinecharts',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'SimpleTreeView',
    icon: IconBorderAll,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Customization',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-customization',
      },
      {
        id: uniqueId(),
        title: 'Expansion',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-expansion',
      },
      {
        id: uniqueId(),
        title: 'Focus',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-focus',
      },
      {
        id: uniqueId(),
        title: 'Items',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-items',
      },
      {
        id: uniqueId(),
        title: 'Selection',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-selection',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Forms',
    icon: IconForms,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Form Elements',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Autocomplete',
            icon: IconPoint,
            href: '/forms/form-elements/autocomplete',
          },
          {
            id: uniqueId(),
            title: 'Button',
            icon: IconPoint,
            href: '/forms/form-elements/button',
          },
          {
            id: uniqueId(),
            title: 'Checkbox',
            icon: IconPoint,
            href: '/forms/form-elements/checkbox',
          },
          {
            id: uniqueId(),
            title: 'Radio',
            icon: IconPoint,
            href: '/forms/form-elements/radio',
          },
          {
            id: uniqueId(),
            title: 'Slider',
            icon: IconPoint,
            href: '/forms/form-elements/slider',
          },
          {
            id: uniqueId(),
            title: 'Date Time',
            icon: IconPoint,
            href: '/forms/form-elements/date-time',
          },
          {
            id: uniqueId(),
            title: 'Switch',
            icon: IconPoint,
            href: '/forms/form-elements/switch',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Form Layouts',
        icon: IconPoint,
        href: '/forms/form-layouts',
      },
      {
        id: uniqueId(),
        title: 'Form Custom',
        icon: IconPoint,
        href: '/forms/form-custom',
      },
      {
        id: uniqueId(),
        title: 'Form Wizard',
        icon: IconPoint,
        href: '/forms/form-wizard',
      },
      {
        id: uniqueId(),
        title: 'Form Validation',
        icon: IconPoint,
        href: '/forms/form-validation',
      },
      {
        id: uniqueId(),
        title: 'Form Horizontal',
        icon: IconPoint,
        href: '/forms/form-horizontal',
      },
      {
        id: uniqueId(),
        title: 'Form Vertical',
        icon: IconPoint,
        href: '/forms/form-vertical',
      },
      {
        id: uniqueId(),
        title: 'Tiptap Editor',
        icon: IconPoint,
        href: '/forms/form-tiptap',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tables',
    icon: IconBorderAll,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Basic Table',
        icon: IconPoint,
        href: '/tables/basic',
      },
      {
        id: uniqueId(),
        title: 'Enhanced Table',
        icon: IconPoint,
        href: '/tables/enhanced',
      },
      {
        id: uniqueId(),
        title: 'Pagination Table',
        icon: IconPoint,
        href: '/tables/pagination',
      },
      {
        id: uniqueId(),
        title: 'Fixed Header Table',
        icon: IconPoint,
        href: '/tables/fixed-header',
      },
      {
        id: uniqueId(),
        title: 'Collapsible Table',
        icon: IconPoint,
        href: '/tables/collapsible',
      },
      {
        id: uniqueId(),
        title: 'Search Table',
        icon: IconPoint,
        href: '/tables/search',
      },
      {
        id: uniqueId(),
        title: 'React Tables',
        icon: IconPoint,
        href: '#',
        children: [
          {
            id: uniqueId(),
            title: 'Basic',
            icon: IconPoint,
            href: '/react-tables/basic',
          },
          {
            id: uniqueId(),
            title: 'Column Visibility',
            icon: IconPoint,
            href: '/react-tables/column-visiblity',
          },
          {
            id: uniqueId(),
            title: 'Dense',
            icon: IconPoint,
            href: '/react-tables/dense',
          },
          {
            id: uniqueId(),
            title: 'Drag Drop',
            icon: IconPoint,
            href: '/react-tables/drag-drop',
          },
          {
            id: uniqueId(),
            title: 'Editable',
            icon: IconPoint,
            href: '/react-tables/editable',
          },
          {
            id: uniqueId(),
            title: 'Empty',
            icon: IconPoint,
            href: '/react-tables/empty',
          },
          {
            id: uniqueId(),
            title: 'Expanding',
            icon: IconPoint,
            href: '/react-tables/expanding',
          },
          {
            id: uniqueId(),
            title: 'Filter',
            icon: IconPoint,
            href: '/react-tables/filter',
          },
          {
            id: uniqueId(),
            title: 'Pagination',
            icon: IconPoint,
            href: '/react-tables/pagination',
          },
          {
            id: uniqueId(),
            title: 'Row Selection',
            icon: IconPoint,
            href: '/react-tables/row-selection',
          },
          {
            id: uniqueId(),
            title: 'Sorting',
            icon: IconPoint,
            href: '/react-tables/sorting',
          },
          {
            id: uniqueId(),
            title: 'Sticky',
            icon: IconPoint,
            href: '/react-tables/sticky',
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Mui Charts',
    icon: IconChartHistogram,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Bar Charts',
        icon: IconPoint,
        href: '/muicharts/barcharts',
      },
      {
        id: uniqueId(),
        title: 'Gauge Charts',
        icon: IconPoint,
        href: '/muicharts/gaugecharts',
      },
      {
        id: uniqueId(),
        title: 'Line Charts Area',
        icon: IconPoint,
        href: '/muicharts/linecharts/area',
      },
      {
        id: uniqueId(),
        title: 'Line Charts',
        icon: IconPoint,
        href: '/muicharts/linecharts/line',
      },
      {
        id: uniqueId(),
        title: 'Pie Charts',
        icon: IconPoint,
        href: '/muicharts/piecharts',
      },
      {
        id: uniqueId(),
        title: 'Scatter Charts',
        icon: IconPoint,
        href: '/muicharts/scattercharts',
      },
      {
        id: uniqueId(),
        title: 'Sparkline Charts',
        icon: IconPoint,
        href: '/muicharts/sparklinecharts',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'SimpleTreeView',
    icon: IconBorderAll,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Customization',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-customization',
      },
      {
        id: uniqueId(),
        title: 'Expansion',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-expansion',
      },
      {
        id: uniqueId(),
        title: 'Focus',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-focus',
      },
      {
        id: uniqueId(),
        title: 'Items',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-items',
      },
      {
        id: uniqueId(),
        title: 'Selection',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-selection',
      },
    ],
  },

  {
    navlabel: true,
    subheader: '📡 Raydar',
  },
  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconLayoutDashboard,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Analytics',
        icon: IconPoint,
        href: '/raydar/dashboard/analytics',
      },
      {
        id: uniqueId(),
        title: 'eCommerce',
        icon: IconPoint,
        href: '/raydar/dashboard/ecommerce',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Pages',
    icon: IconFiles,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Calendar',
        icon: IconPoint,
        href: '/raydar/pages/calendar',
      },
      {
        id: uniqueId(),
        title: 'Invoice',
        icon: IconPoint,
        href: '/raydar/pages/invoice',
      },
      {
        id: uniqueId(),
        title: 'Welcome',
        icon: IconPoint,
        href: '/raydar/pages/welcome',
      },
      {
        id: uniqueId(),
        title: 'FAQs',
        icon: IconPoint,
        href: '/raydar/pages/faqs',
      },
      {
        id: uniqueId(),
        title: 'Timeline',
        icon: IconPoint,
        href: '/raydar/pages/timeline',
      },
      {
        id: uniqueId(),
        title: 'Pricing',
        icon: IconPoint,
        href: '/raydar/pages/pricing',
      },
      {
        id: uniqueId(),
        title: 'Widgets',
        icon: IconPoint,
        href: '/raydar/pages/widgets',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Base UI',
    icon: IconComponents,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Accordions',
        icon: IconPoint,
        href: '/raydar/ui/accordions',
      },
      {
        id: uniqueId(),
        title: 'Alerts',
        icon: IconPoint,
        href: '/raydar/ui/alerts',
      },
      {
        id: uniqueId(),
        title: 'Avatars',
        icon: IconPoint,
        href: '/raydar/ui/avatars',
      },
      {
        id: uniqueId(),
        title: 'Badges',
        icon: IconPoint,
        href: '/raydar/ui/badges',
      },
      {
        id: uniqueId(),
        title: 'Breadcrumb',
        icon: IconPoint,
        href: '/raydar/ui/breadcrumb',
      },
      {
        id: uniqueId(),
        title: 'Buttons',
        icon: IconPoint,
        href: '/raydar/ui/buttons',
      },
      {
        id: uniqueId(),
        title: 'Cards',
        icon: IconPoint,
        href: '/raydar/ui/cards',
      },
      {
        id: uniqueId(),
        title: 'Carousel',
        icon: IconPoint,
        href: '/raydar/ui/carousel',
      },
      {
        id: uniqueId(),
        title: 'Collapse',
        icon: IconPoint,
        href: '/raydar/ui/collapse',
      },
      {
        id: uniqueId(),
        title: 'Dropdowns',
        icon: IconPoint,
        href: '/raydar/ui/dropdowns',
      },
      {
        id: uniqueId(),
        title: 'List Group',
        icon: IconPoint,
        href: '/raydar/ui/list-group',
      },
      {
        id: uniqueId(),
        title: 'Modals',
        icon: IconPoint,
        href: '/raydar/ui/modals',
      },
      {
        id: uniqueId(),
        title: 'Tabs',
        icon: IconPoint,
        href: '/raydar/ui/tabs',
      },
      {
        id: uniqueId(),
        title: 'Offcanvas',
        icon: IconPoint,
        href: '/raydar/ui/offcanvas',
      },
      {
        id: uniqueId(),
        title: 'Pagination',
        icon: IconPoint,
        href: '/raydar/ui/pagination',
      },
      {
        id: uniqueId(),
        title: 'Placeholders',
        icon: IconPoint,
        href: '/raydar/ui/placeholders',
      },
      {
        id: uniqueId(),
        title: 'Popovers',
        icon: IconPoint,
        href: '/raydar/ui/popovers',
      },
      {
        id: uniqueId(),
        title: 'Progress',
        icon: IconPoint,
        href: '/raydar/ui/progress',
      },
      {
        id: uniqueId(),
        title: 'Spinners',
        icon: IconPoint,
        href: '/raydar/ui/spinners',
      },
      {
        id: uniqueId(),
        title: 'Toasts',
        icon: IconPoint,
        href: '/raydar/ui/toasts',
      },
      {
        id: uniqueId(),
        title: 'Tooltips',
        icon: IconPoint,
        href: '/raydar/ui/tooltips',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Advanced UI',
    icon: IconStar,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Ratings',
        icon: IconPoint,
        href: '/raydar/advanced/ratings',
      },
      {
        id: uniqueId(),
        title: 'Sweet Alerts',
        icon: IconPoint,
        href: '/raydar/advanced/alert',
      },
      {
        id: uniqueId(),
        title: 'Swiper Slider',
        icon: IconPoint,
        href: '/raydar/advanced/swiper',
      },
      {
        id: uniqueId(),
        title: 'Scrollbar',
        icon: IconPoint,
        href: '/raydar/advanced/scrollbar',
      },
      {
        id: uniqueId(),
        title: 'Toastify',
        icon: IconPoint,
        href: '/raydar/advanced/toastify',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Advanced Charts',
    icon: IconChartLine,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Area Charts',
        icon: IconPoint,
        href: '/raydar/charts/area',
      },
      {
        id: uniqueId(),
        title: 'Bar Charts',
        icon: IconPoint,
        href: '/raydar/charts/bar',
      },
      {
        id: uniqueId(),
        title: 'Bubble Charts',
        icon: IconPoint,
        href: '/raydar/charts/bubble',
      },
      {
        id: uniqueId(),
        title: 'Candlestick',
        icon: IconPoint,
        href: '/raydar/charts/candlestick',
      },
      {
        id: uniqueId(),
        title: 'Column Charts',
        icon: IconPoint,
        href: '/raydar/charts/column',
      },
      {
        id: uniqueId(),
        title: 'Heatmap',
        icon: IconPoint,
        href: '/raydar/charts/heatmap',
      },
      {
        id: uniqueId(),
        title: 'Mixed Charts',
        icon: IconPoint,
        href: '/raydar/charts/mixed',
      },
      {
        id: uniqueId(),
        title: 'Timeline Charts',
        icon: IconPoint,
        href: '/raydar/charts/timeline',
      },
      {
        id: uniqueId(),
        title: 'Treemap Charts',
        icon: IconPoint,
        href: '/raydar/charts/treemap',
      },
      {
        id: uniqueId(),
        title: 'Boxplot Charts',
        icon: IconPoint,
        href: '/raydar/charts/boxplot',
      },
      {
        id: uniqueId(),
        title: 'Radar Charts',
        icon: IconPoint,
        href: '/raydar/charts/radar',
      },
      {
        id: uniqueId(),
        title: 'Radial Bar',
        icon: IconPoint,
        href: '/raydar/charts/radial-bar',
      },
      {
        id: uniqueId(),
        title: 'Scatter Charts',
        icon: IconPoint,
        href: '/raydar/charts/scatter',
      },
      {
        id: uniqueId(),
        title: 'Polar Charts',
        icon: IconPoint,
        href: '/raydar/charts/polar',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Vector Maps',
    icon: IconMap,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'World Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/world',
      },
      {
        id: uniqueId(),
        title: 'USA Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/usa',
      },
      {
        id: uniqueId(),
        title: 'Canada Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/canada',
      },
      {
        id: uniqueId(),
        title: 'Russia Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/russia',
      },
      {
        id: uniqueId(),
        title: 'Italy Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/italy',
      },
      {
        id: uniqueId(),
        title: 'Spain Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/spain',
      },
      {
        id: uniqueId(),
        title: 'Iraq Map',
        icon: IconPoint,
        href: '/raydar/vector-maps/iraq',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Advanced Forms',
    icon: IconAdjustments,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Form Validation',
        icon: IconPoint,
        href: '/raydar/forms/validation',
      },
      {
        id: uniqueId(),
        title: 'Form Wizard',
        icon: IconPoint,
        href: '/raydar/forms/wizard',
      },
      {
        id: uniqueId(),
        title: 'File Uploads',
        icon: IconPoint,
        href: '/raydar/forms/file-uploads',
      },
      {
        id: uniqueId(),
        title: 'Advanced Editors',
        icon: IconPoint,
        href: '/raydar/forms/editors',
      },
      {
        id: uniqueId(),
        title: 'Input Mask',
        icon: IconPoint,
        href: '/raydar/forms/input-mask',
      },
      {
        id: uniqueId(),
        title: 'Range Slider',
        icon: IconPoint,
        href: '/raydar/forms/slider',
      },
      {
        id: uniqueId(),
        title: 'Date Picker',
        icon: IconPoint,
        href: '/raydar/forms/flat-picker',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Enhanced Tables',
    icon: IconBorderAll,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'GridJS Tables',
        icon: IconPoint,
        href: '/raydar/tables/gridjs',
      },
      {
        id: uniqueId(),
        title: 'Advanced Basic',
        icon: IconPoint,
        href: '/raydar/tables/basic',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Widgets',
    icon: IconComponents,
    href: '/raydar/widgets',
  },
  {
    id: uniqueId(),
    title: 'Icon Libraries',
    icon: IconBox,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'BoxIcons',
        icon: IconPoint,
        href: '/raydar/icons/boxicons',
      },
      {
        id: uniqueId(),
        title: 'Solar Icons',
        icon: IconPoint,
        href: '/raydar/icons/solar',
      },
    ],
  },

  {
    navlabel: true,
    subheader: '🗂️ MISC',
  },
  {
    id: uniqueId(),
    title: 'eCommerce',
    icon: IconPoint,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Shop',
        icon: IconPoint,
        href: '/apps/ecommerce/shop',
      },
      {
        id: uniqueId(),
        title: 'Product List',
        icon: IconPoint,
        href: '/apps/ecommerce/eco-product-list',
      },
      {
        id: uniqueId(),
        title: 'Checkout',
        icon: IconPoint,
        href: '/apps/ecommerce/eco-checkout',
      },
      {
        id: uniqueId(),
        title: 'Add Product',
        icon: IconPoint,
        href: '/apps/ecommerce/add-product',
      },
      {
        id: uniqueId(),
        title: 'Edit Product',
        icon: IconPoint,
        href: '/apps/ecommerce/edit-product',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Invoice',
    icon: IconPoint,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Invoice List',
        icon: IconPoint,
        href: '/apps/invoice/list',
      },
      {
        id: uniqueId(),
        title: 'Create Invoice',
        icon: IconPoint,
        href: '/apps/invoice/create',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'User Profile',
    icon: IconPoint,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Followers',
        icon: IconPoint,
        href: '/apps/followers',
      },
      {
        id: uniqueId(),
        title: 'Friends',
        icon: IconPoint,
        href: '/apps/friends',
      },
      {
        id: uniqueId(),
        title: 'Gallery',
        icon: IconPoint,
        href: '/apps/gallery',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'CMS',
    icon: IconPoint,
    href: '#',
    children: [
      {
        id: uniqueId(),
        title: 'Page Editor',
        icon: IconPoint,
        href: '/apps/cms/page-editor',
      },
      {
        id: uniqueId(),
        title: 'Enhanced Editor',
        icon: IconPoint,
        href: '/apps/cms/page-editor-enhanced',
      },
      {
        id: uniqueId(),
        title: 'Legacy Editor',
        icon: IconPoint,
        href: '/apps/cms/page-editor-legacy',
      },
    ],
  },
];

export const getMenuItems = (user: any) => {
  if (user && (user.role === 'super_admin' || user.role === 'admin')) {
    return Menuitems;
  }
  // For non-admin users, show only Notes App and Liturgical Calendar under Apps, and Users Guide under Quick Links
  return [
    {
      navlabel: true,
      subheader: 'Dashboard',
    },
    {
      id: uniqueId(),
      title: 'Enhanced Modern Dashboard',
      icon: IconHome,
      href: '/dashboards/modern',
    },
    {
      navlabel: true,
      subheader: 'Apps',
    },
    {
      id: uniqueId(),
      title: 'Notes',
      icon: IconNotes,
      href: '/apps/notes',
    },
    {
      id: uniqueId(),
      title: 'Orthodox Liturgical Calendar',
      icon: IconCalendar,
      href: '/apps/liturgical-calendar',
    },
    {
      navlabel: true,
      subheader: '💬 Social',
    },
    {
      id: uniqueId(),
      title: 'Blog',
      icon: IconWriting,
      href: '/social/blog',
    },
    {
      id: uniqueId(),
      title: 'Friends',
      icon: IconUserPlus,
      href: '/social/friends',
    },
    {
      id: uniqueId(),
      title: 'Chat',
      icon: IconMessage,
      href: '/social/chat',
    },
    {
      id: uniqueId(),
      title: 'Notifications',
      icon: IconBell,
      href: '/social/notifications',
    },
    {
      navlabel: true,
      subheader: '🛠️ Developer Tools',
    },
    {
      id: uniqueId(),
      title: 'Site Structure Visualizer',
      icon: IconSitemap,
      href: '/tools/site-structure',
    },
    {
      navlabel: true,
      subheader: 'Quick Links',
    },
    {
      id: uniqueId(),
      title: 'Users Guide',
      icon: IconFileDescription,
      href: '/frontend-pages/coming-soon',
    },
  ];
};

export default Menuitems;
